name: controllerhub_mobile
description: "Turn your phone into a game controller."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.4.2
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.5.5
  uuid: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/controllerhub-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/controllerhub-icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#0D0F14"
  adaptive_icon_foreground: "assets/controllerhub-icon.png"